general.import = ["/home/char/.alacritty-colorscheme/themes/dark_pastels.toml"]
#tabspaces = 4
[cursor]
blink_interval = 500
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
LANG = "en_US.UTF-8"
# TERM = "tmux-256color"

[font]
# draw_bold_text_with_bright_colors = true
size = 11

[font.normal]
style= "Bold"
family = "JetBrainsMono Nerd Font"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[scrolling]
#auto_scroll = false
history = 10000
multiplier = 3

[window]
opacity = 0.8
title = "Alacritty"
padding.x = 10
padding.y = 2
decorations = "Full"

[window.class]
general = "Alacritty"
instance = "Alacritty"
