{
  pkgs,
  lib,
  ...
}:
let
  # Detect platform
  isDarwin = pkgs.stdenv.isDarwin;
  isLinux = pkgs.stdenv.isLinux;

  # Platform-specific paths
  homeDir = if isDarwin then "/Users/char" else "/home/char";
  projectDir = "${homeDir}/projects/personal/code";
in
{
  programs.home-manager.enable = true;

  home.username = "char";
  home.homeDirectory = homeDir;

  # Suppress version mismatch warning
  home.enableNixpkgsReleaseCheck = false;

  home.sessionVariables = {
    MY_FOLDER = homeDir;
    CODE_PATH = "${homeDir}/projects/personal/code/";
    EDITOR = "nvim";
  };

  home.sessionPath = [
    "${projectDir}/dot-files/scripts"
  ];

  # Password store (Linux only for now, uses wayland extensions)
  programs.password-store = lib.mkIf isLinux {
    enable = true;
    package = pkgs.pass-wayland.withExtensions (
      exts: with exts; [
        pass-otp
        pass-import
        pass-audit
      ]
    );
    settings.PASSWORD_STORE_DIR = "${homeDir}/.password-store";
  };

  # Shared dotfiles (work on both platforms)
  home.file = {
    scripts = {
      recursive = true;
      target = "./local/bin/";
      source = "${projectDir}/dot-files/scripts";
    };
    ".local/bin/xdg-open".text = ''
      #!/usr/bin/env bash
      if [[ "$1" =~ ^https?:// ]]; then
          firefox "$1" &
      else
          /run/current-system/sw/bin/xdg-open "$@"
      fi
    '';
    ".local/bin/xdg-open".executable = true;
    newsboat = {
      recursive = true;
      target = "./.newsboat";
      source = "${projectDir}/dot-files/newsboat";
    };
    custom-zsh = {
      recursive = false;
      target = ".zshrc";
      source = "${projectDir}/dot-files/zsh/.zshrc";
    };
    tmux = {
      recursive = false;
      target = "./.tmux.conf";
      source = "${projectDir}/dot-files/tmux/.tmux.conf";
    };
    tmuxinator = {
      recursive = true;
      target = ".config/tmuxinator";
      source = "${projectDir}/dot-files/tmuxinator";
    };
    alacritty = {
      recursive = true;
      target = ".config/alacritty/";
      source = "${projectDir}/dot-files/alacritty";
    };
    nvim = {
      recursive = true;
      target = ".config/nvim";
      source = "${projectDir}/dot-files/nvim";
    };
  }
  // lib.optionalAttrs isLinux {
    # Linux-specific dotfiles
    hypr = {
      recursive = true;
      target = ".config/hypr";
      source = "${projectDir}/dot-files/hypr";
    };
    rofi = {
      recursive = false;
      target = ".config/rofi/config.rasi";
      source = "${projectDir}/dot-files/rofi/config.rasi";
    };
    rofi-theme = {
      recursive = false;
      target = ".local/share/rofi/themes/";
      source = "${projectDir}/dot-files/rofi/";
    };
    # waybar = {
    #   recursive = true;
    #   target = ".config/waybar";
    #   source = "${projectDir}/dot-files/waybar";
    # };
  }
  // lib.optionalAttrs isDarwin {
    # macOS-specific dotfiles
    aerospace = {
      recursive = true;
      target = ".config/aerospace/";
      source = "${projectDir}/dot-files/aerospace";
    };
  };

  # Linux-specific dconf settings
  dconf = lib.mkIf isLinux {
    enable = true;
    settings."org/gnome/desktop/interface".color-scheme = "prefer-dark";
  };

  # Caelestia shell configuration (Linux only)
  programs.caelestia = lib.mkIf isLinux (
    let
      caelestiaSettings = import ./caelestia-config.nix { inherit homeDir; };
    in
    {
      enable = true;
      systemd.enable = true;
      settings = caelestiaSettings;
      cli = {
        enable = true; # Also add caelestia-cli to path
      };
    }
  );

  # Force overwrite caelestia shell.json to resolve conflicts
  xdg.configFile."caelestia/shell.json".force = lib.mkIf isLinux true;

  # Stub so Hyprland can source it before caelestia writes the real file
  xdg.configFile."caelestia/hypr-user.conf" = lib.mkIf isLinux {
    text = "# Generated by caelestia-shell at runtime\n";
    force = true;
  };

  programs.gpg = {
    enable = true;
    mutableTrust = true;
    publicKeys = [
      {
        source = ../gpg-key/charlie-gpg-public.asc;
        trust = 5;
      }
    ];
  };

  programs.git = {
    enable = true;
    settings = {
      user = {
        name = "cargaona";
        email = "carlos.gaona@cloudie.dev";
        signingKey = "C8CC693AA363666A00905B7CB4A49FC0D3283270";
      };
      commit.gpgSign = true;
      gpg.format = "openpgp";
      init.defaultBranch = "master";
      pull.rebase = true;
    };
  };

  programs.ssh = {
    enable = true;
    enableDefaultConfig = false;
    matchBlocks."*".forwardAgent = true;
  };

  # OpenCode configuration
  xdg.configFile."opencode/opencode.jsonc" = {
    text = builtins.toJSON {
      "$schema" = "https://opencode.ai/config.json";
      plugin = [
        "opencode-anthropic-auth@latest"
      ];
      provider = {
        ollama = {
          npm = "@ai-sdk/openai-compatible";
          name = "Ollama (local)";
          options = {
            baseURL = "http://localhost:11434/v1";
          };
          models = {
            "qwen2.5-coder:7b" = {
              name = "qwen2.5";
              options = {
                toolCallStreaming = false;
                structuredOutputs = false;
              };
            };
            "qwen3:8b" = {
              name = "qwen3";
            };
            "deepseek-r1:7b" = {
              name = "deepseek-r1";
            };
            "llama3.2:3b" = {
              name = "llama3.2";
            };
            "qwen3-coder:30b" = {
              name = "qwen3-coder";
            };
          };
        };
      };
    };
    # Force overwrite to ensure Nix manages this file
    force = true;
  };

  # Brave PWA-style desktop entries
  xdg.desktopEntries = lib.mkIf isLinux {
    gemini = {
      name = "Gemini";
      genericName = "AI Assistant";
      exec = "brave --app=https://gemini.google.com";
      terminal = false;
      icon = "brave";
      type = "Application";
      categories = [
        "Network"
        "WebBrowser"
      ];
    };
    chatgpt = {
      name = "ChatGPT";
      genericName = "AI Assistant";
      exec = "brave --app=https://chat.openai.com";
      terminal = false;
      icon = "brave";
      type = "Application";
      categories = [
        "Network"
        "WebBrowser"
      ];
    };
    feed = {
      name = "Feed";
      genericName = "RSS Reader";
      exec = "brave --app=https://feed.charlei.lat";
      terminal = false;
      icon = "brave";
      type = "Application";
      categories = [
        "Network"
        "News"
      ];
    };
    homeassistant = {
      name = "Home Assistant";
      genericName = "Smart Home";
      exec = "brave --app=https://ha.charlei.lat";
      terminal = false;
      icon = "brave";
      type = "Application";
      categories = [
        "Network"
        "Utility"
      ];
    };
    whatsapp = {
      name = "WhatsApp";
      genericName = "Messaging";
      exec = "brave --app=https://web.whatsapp.com";
      terminal = false;
      icon = "brave";
      type = "Application";
      categories = [
        "Network"
        "InstantMessaging"
      ];
    };
    notebooklm = {
      name = "NotebookLM";
      genericName = "AI Notes";
      exec = "brave --app=https://notebooklm.google.com";
      terminal = false;
      icon = "brave";
      type = "Application";
      categories = [
        "Network"
        "Office"
      ];
    };
    grok = {
      name = "Grok";
      genericName = "AI Assistant";
      exec = "brave --app=https://x.com/i/grok";
      terminal = false;
      icon = "brave";
      type = "Application";
      categories = [
        "Network"
        "WebBrowser"
      ];
    };
    gmail = {
      name = "Gmail";
      genericName = "Email";
      exec = "brave --app=https://mail.google.com";
      terminal = false;
      icon = "brave";
      type = "Application";
      categories = [
        "Network"
        "Email"
      ];
    };
    notion-calendar = {
      name = "Notion Calendar";
      genericName = "Calendar";
      exec = "brave --app=https://calendar.notion.com";
      terminal = false;
      icon = "brave";
      type = "Application";
      categories = [
        "Network"
        "Office"
        "Calendar"
      ];
    };
    photos = {
      name = "Photos";
      genericName = "Photo Gallery";
      exec = "brave --app=https://photos.charlei.lat";
      terminal = false;
      icon = "brave";
      type = "Application";
      categories = [
        "Network"
        "Graphics"
      ];
    };
  };

  # Brave browser preferences - disable password manager
  xdg.configFile."BraveSoftware/Brave-Browser/NativeMessagingHosts/.keep".text = lib.mkIf isLinux "";
  xdg.configFile."brave-flags.conf" = lib.mkIf isLinux {
    text = ''
      --password-store=basic
      --disable-features=PasswordManager
    '';
  };

  home.stateVersion = "25.11";
}
