{
  pkgs,
  lib,
  isDesktop ? false,
  ...
}:
let
  homeDir = "/home/char";
  projectDir = "${homeDir}/projects/personal/code";
  isLinux = pkgs.stdenv.isLinux;

in
{
  # Caelestia shell configuration (desktop Linux only)
  # Uses isDesktop from extraSpecialArgs (not pkgs) so it's safe in imports.
  # The caelestia-shell HM module that declares programs.caelestia is only
  # imported on desktop hosts (costanza/elaine), so we must guard the import
  # here to avoid referencing an undefined option on non-desktop hosts.
  imports = lib.optional isDesktop (
    { pkgs, lib, ... }:
    let
      caelestiaSettings = import ./caelestia-config.nix { inherit homeDir; };
    in
    {
      programs.caelestia = {
        enable = true;
        systemd.enable = true;
        settings = caelestiaSettings;
        cli = {
          enable = true; # Also add caelestia-cli to path
        };
      };

      # Force overwrite caelestia shell.json to resolve conflicts
      xdg.configFile."caelestia/shell.json".force = true;

      # Stub so Hyprland can source it before caelestia writes the real file
      xdg.configFile."caelestia/hypr-user.conf" = {
        text = "# Generated by caelestia-shell at runtime\n";
        force = true;
      };
    }
  );

  programs.home-manager.enable = true;

  home.username = "char";
  home.homeDirectory = homeDir;

  # Suppress version mismatch warning
  home.enableNixpkgsReleaseCheck = false;

  home.sessionVariables = {
    MY_FOLDER = homeDir;
    CODE_PATH = "${homeDir}/projects/personal/code/";
    EDITOR = "nvim";
  };

  home.sessionPath = [
    "${projectDir}/dot-files/scripts"
  ];

  programs.beets = lib.mkIf (!isDesktop) {
    enable = true;
    package = pkgs.python3Packages.beets;
    settings = {
      directory = "/mnt/seagate/music/";
      library = "/mnt/seagate/music/library.db";
      move = true;
      delete = true;
      asciify_path = true;

      plugins = [
        "missing"
        "web"
        "fetchart"
        "embedart"
        "duplicates"
        "musicbrainz"
        "lastimport"
        "smartplaylist"
        "subsonicupdate"
        "subsonicplaylist"
      ];

      lastimport = {
        user = "notstolen";
      };

      smartplaylist = {
        playlist_dir = "/mnt/seagate/music/playlists";
        relative_to = "/mnt/seagate/music";
        forward_slash = false;
        playlists = [
          {
            name = "Most Played.m3u";
            query = "play_count:5..";
          }
          {
            name = "Recently Added.m3u";
            query = "added:-1m..";
          }
        ];
      };

      paths = {
        "albumtype:ep" = "$albumartist/$album [EP] ($original_year)/$track - $title";
        "albumtype:single" = "$albumartist/$album [Single] ($original_year)/$track - $title";
        default = "$albumartist/$album ($original_year)/$track - $title";
      };

      fetchart = {
        quality = 65;
        sources = "coverart itunes amazon fanarttv";
        store_source = true;
        auto = true;
        maxwidth = 300;
      };

      embedart = {
        auto = true;
        maxwidth = 300;
      };
    };
  };

  programs.password-store = {
    enable = true;
    package = pkgs.pass-wayland.withExtensions (
      exts: with exts; [
        pass-otp
        pass-import
        pass-audit
      ]
    );
    settings.PASSWORD_STORE_DIR = "${homeDir}/.password-store";
  };

  # Shared dotfiles (work on both platforms)
  home.file = {
    scripts = {
      recursive = true;
      target = "./local/bin/";
      source = "${projectDir}/dot-files/scripts";
    };
    ".local/bin/xdg-open".text = ''
      #!/usr/bin/env bash
      if [[ "$1" =~ ^https?:// ]]; then
          firefox "$1" &
      else
          /run/current-system/sw/bin/xdg-open "$@"
      fi
    '';
    ".local/bin/xdg-open".executable = true;
    newsboat = {
      recursive = true;
      target = "./.newsboat";
      source = "${projectDir}/dot-files/newsboat";
    };
    custom-zsh = {
      recursive = false;
      target = ".zshrc";
      source = "${projectDir}/dot-files/zsh/.zshrc";
    };
    tmux = {
      recursive = false;
      target = "./.tmux.conf";
      source = "${projectDir}/dot-files/tmux/.tmux.conf";
    };
    tmuxinator = {
      recursive = true;
      target = ".config/tmuxinator";
      source = "${projectDir}/dot-files/tmuxinator";
    };
    alacritty = {
      recursive = true;
      target = ".config/alacritty/";
      source = "${projectDir}/dot-files/alacritty";
    };
    nvim = {
      recursive = true;
      target = ".config/nvim";
      source = "${projectDir}/dot-files/nvim";
    };
  }
  // lib.optionalAttrs isLinux {
    # Linux-specific dotfiles
    hypr = {
      recursive = true;
      target = ".config/hypr";
      source = "${projectDir}/dot-files/hypr";
    };
    rofi = {
      recursive = false;
      target = ".config/rofi/config.rasi";
      source = "${projectDir}/dot-files/rofi/config.rasi";
    };
    rofi-theme = {
      recursive = false;
      target = ".local/share/rofi/themes/";
      source = "${projectDir}/dot-files/rofi/";
    };
    # waybar = {
    #   recursive = true;
    #   target = ".config/waybar";
    #   source = "${projectDir}/dot-files/waybar";
    # };
  };

  dconf = lib.mkIf isDesktop {
    enable = true;
    settings."org/gnome/desktop/interface".color-scheme = "prefer-dark";
  };

  programs.gpg = {
    enable = true;
    mutableTrust = true;
    publicKeys = [
      {
        source = ../gpg-key/charlie-gpg-public.asc;
        trust = 5;
      }
    ];
  };

  programs.git = {
    enable = true;
    settings = {
      user = {
        name = "cargaona";
        email = "carlos.gaona@cloudie.dev";
        # signingKey = "C8CC693AA363666A00905B7CB4A49FC0D3283270";
      };
      # commit.gpgSign = true;
      gpg.format = "openpgp";
      init.defaultBranch = "master";
      pull.rebase = true;
    };
  };

  programs.ssh = {
    enable = true;
    enableDefaultConfig = false;
    matchBlocks."*".forwardAgent = true;
  };

  # OpenCode configuration
  xdg.configFile."opencode/opencode.jsonc" = {
    text = builtins.toJSON {
      "$schema" = "https://opencode.ai/config.json";
      plugin = [
        "opencode-claude-auth"
      ];
      provider = {
        ollama = {
          npm = "@ai-sdk/openai-compatible";
          name = "Ollama (local)";
          options = {
            baseURL = "http://localhost:11434/v1";
          };
          models = {
            "qwen2.5-coder:7b" = {
              name = "qwen2.5";
              options = {
                toolCallStreaming = false;
                structuredOutputs = false;
              };
            };
            "qwen3:8b" = {
              name = "qwen3";
            };
            "deepseek-r1:7b" = {
              name = "deepseek-r1";
            };
            "llama3.2:3b" = {
              name = "llama3.2";
            };
            "qwen3-coder:30b" = {
              name = "qwen3-coder";
            };
          };
        };
      };
    };
    # Force overwrite to ensure Nix manages this file
    force = true;
  };

  # Brave PWA-style desktop entries
  xdg.desktopEntries = lib.mkIf isLinux {
    gemini = {
      name = "Gemini";
      genericName = "AI Assistant";
      exec = "brave --app=https://gemini.google.com";
      terminal = false;
      icon = "google";
      type = "Application";
      categories = [
        "Network"
        "WebBrowser"
      ];
    };
    chatgpt = {
      name = "ChatGPT";
      genericName = "AI Assistant";
      exec = "brave --app=https://chat.openai.com";
      terminal = false;
      icon = "chatgpt";
      type = "Application";
      categories = [
        "Network"
        "WebBrowser"
      ];
    };
    feed = {
      name = "Feed";
      genericName = "RSS Reader";
      exec = "brave --app=https://feed.charlei.lat";
      terminal = false;
      icon = "internet-news-reader";
      type = "Application";
      categories = [
        "Network"
        "News"
      ];
    };
    homeassistant = {
      name = "Home Assistant";
      genericName = "Smart Home";
      exec = "brave --app=https://ha.charlei.lat";
      terminal = false;
      icon = "home-assistant";
      type = "Application";
      categories = [
        "Network"
        "Utility"
      ];
    };
    whatsapp = {
      name = "WhatsApp";
      genericName = "Messaging";
      exec = "brave --app=https://web.whatsapp.com";
      terminal = false;
      icon = "whatsapp";
      type = "Application";
      categories = [
        "Network"
        "InstantMessaging"
      ];
    };
    notebooklm = {
      name = "NotebookLM";
      genericName = "AI Notes";
      exec = "brave --app=https://notebooklm.google.com";
      terminal = false;
      icon = "notebook";
      type = "Application";
      categories = [
        "Network"
        "Office"
      ];
    };
    grok = {
      name = "Grok";
      genericName = "AI Assistant";
      exec = "brave --app=https://x.com/i/grok";
      terminal = false;
      icon = "twitter";
      type = "Application";
      categories = [
        "Network"
        "WebBrowser"
      ];
    };
    gmail = {
      name = "Gmail";
      genericName = "Email";
      exec = "brave --app=https://mail.google.com";
      terminal = false;
      icon = "gmail";
      type = "Application";
      categories = [
        "Network"
        "Email"
      ];
    };
    notion-calendar = {
      name = "Notion Calendar";
      genericName = "Calendar";
      exec = "brave --app=https://calendar.notion.com";
      terminal = false;
      icon = "calendar";
      type = "Application";
      categories = [
        "Network"
        "Office"
        "Calendar"
      ];
    };
    photos = {
      name = "Photos";
      genericName = "Photo Gallery";
      exec = "brave --app=https://photos.charlei.lat";
      terminal = false;
      icon = "multimedia-photo-manager";
      type = "Application";
      categories = [
        "Network"
        "Graphics"
      ];
    };
    feishin = {
      name = "Feishin";
      genericName = "Music Streaming";
      exec = "brave --app=https://feishin.charlei.lat";
      terminal = false;
      icon = "multimedia-audio-player";
      type = "Application";
      categories = [
        "Audio"
        "Music"
        "Network"
      ];
    };
    emby = {
      name = "Emby";
      genericName = "Media Server";
      exec = "brave --app=https://emby.charlei.xyz";
      terminal = false;
      icon = "emby";
      type = "Application";
      categories = [
        "Audio"
        "Video"
        "Network"
      ];
    };
    notion = {
      name = "Notion";
      genericName = "Productivity";
      exec = "brave --app=https://notion.so";
      terminal = false;
      icon = "notion";
      type = "Application";
      categories = [
        "Network"
        "Office"
      ];
    };
    harvest = {
      name = "Harvest";
      genericName = "Time Tracking";
      exec = "brave --app=https://waytoodigital.harvestapp.com/time";
      terminal = false;
      icon = "harvest";
      type = "Application";
      categories = [
        "Network"
        "Office"
      ];
    };
    claude = {
      name = "Claude";
      genericName = "AI Assistant";
      exec = "brave --app=https://claude.ai/new";
      terminal = false;
      icon = "claude";
      type = "Application";
      categories = [
        "Network"
        "Development"
        "Office"
      ];
    };
  };

  home.stateVersion = "25.11";
}
