#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# keyword repetition
xset r rate 250 30
# screen lock
xset s 300 20
xss-lock -- betterlockscreen -l &
setxkbmap -layout us -variant altgr-intl &
cbatticon &
pasystray -g &
nm-applet &
blueman-applet &
TERMINAL=alacritty XDG_SESSION_TYPE=x11 GDK_BACKEND=x11 exec i3 -c /home/char/.config/i3/config
##DESKTOP_SESSION=plasma exec startplasma-x11
