#!bash
shopt -s nullglob globstar

function writePassword {
  if [[ $XDG_CURRENT_DESKTOP == "sway" ]]; then
    echo "type $1" | dotool 
  else
    echo "$1" |  xdotool type --clearmodifiers --file -
  fi
}

rofi_command="rofi -dmenu" 

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | ${rofi_command} "$@")

[[ -n $password ]] || exit

pass_cmd=show
if pass show "$password" | grep -q '^otpauth://'; then
    pass_cmd=otp
fi
if pass show $password | grep -q 'aws_access_key_id'; then
    pass_cmd='aws console'
fi

if [[ $typeit -eq 0 ]]; then
	pass $pass_cmd "$password" -c 2>/dev/null
else
  pswd=$(pass $pass_cmd "$password" | { IFS= read -r pass; printf %s "$pass"; })
  writePassword ${pswd}
fi

